### ISSUE TITLE
win10 2015 

### ISSUE THREAD

**Issue by Andrawzyf** [qaz734913414/Ncnn_FaceTrack#2]
博主你好，我在win10 VS2015 环境下编译不过，没有语法错误，但是编译不过，请问是什么原因呢，你的环境是？
编译环境结果如下
1>d:\vs2015projects\facetrack\facetrack\LandmarkTracking.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(14): error C2059: 语法错误:“namespace”
1>D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(14): error C2334: “{”的前面有意外标记；跳过明显的函数体
1>D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\thr/xthrcommon.h(22): error C2059: 语法错误:“字符串”
1>D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\thr/xthrcommon.h(22): error C2334: “{”的前面有意外标记；跳过明显的函数体
1>D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\thr/xtimec.h(15): error C2059: 语法错误:“字符串”
1>D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\thr/xtimec.h(15): error C2334: “{”的前面有意外标记；跳过明显的函数体
1>D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(20): error C2059: 语法错误:“namespace”
1>D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(20): error C2334: “{”的前面有意外标记；跳过明显的函数体
1>D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(23): error C2059: 语法错误:“namespace”
1>D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(23): error C2334: “{”的前面有意外标记；跳过明显的函数体
1>D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(1181): error C2059: 语法错误:“namespace”
1>D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(1181): error C2334: “{”的前面有意外标记；跳过明显的函数体
1>D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\thr/xtime(13): error C2059: 语法错误:“namespace”
1>D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\thr/xtime(14): error C2334: “{”的前面有意外标记；跳过明显的函数体
1>D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\thr/xthreads.h(15): error C2059: 语法错误:“字符串”
1>D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\thr/xthreads.h(15): error C2334: “{”的前面有意外标记；跳过明显的函数体
1>D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\thr/xthread(18): error C2059: 语法错误:“namespace”
1>D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\thr/xthread(18): error C2334: “{”的前面有意外标记；跳过明显的函数体
1>D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\thread(30): error C2059: 语法错误:“namespace”
1>D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\thread(30): error C2334: “{”的前面有意外标记；跳过明显的函数体
1>D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\mutex(21): error C2059: 语法错误:“namespace”
1>D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\mutex(21): error C2334: “{”的前面有意外标记；跳过明显的函数体
1>main.cpp(59): error C3646: “mutex”: 未知重写说明符
1>  main.cpp(60): note: 参见对正在编译的类 模板 实例化“Face::QueueFPS<T>”的引用
1>main.cpp(59): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>main.cpp(92): error C3646: “mutex”: 未知重写说明符
1>  main.cpp(93): note: 参见对正在编译的类 模板 实例化“Face::Queue<T>”的引用
1>main.cpp(92): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>d:\vs2015projects\facetrack\facetrack\LandmarkTracking.h(61): fatal error C1075: 左侧的 大括号“{” 与文件结尾不匹配
1>  mtcnn.cpp
1>mtcnn.cpp(71): warning C4244: “=”: 从“float”转换到“int”，可能丢失数据
1>mtcnn.cpp(72): warning C4244: “=”: 从“float”转换到“int”，可能丢失数据
1>mtcnn.cpp(73): warning C4244: “=”: 从“float”转换到“int”，可能丢失数据
1>mtcnn.cpp(74): warning C4244: “=”: 从“float”转换到“int”，可能丢失数据
1>mtcnn.cpp(75): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
1>mtcnn.cpp(102): warning C4244: “初始化”: 从“__int64”转换到“int”，可能丢失数据
1>mtcnn.cpp(103): warning C4244: “初始化”: 从“__int64”转换到“int”，可能丢失数据
1>mtcnn.cpp(104): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
1>mtcnn.cpp(105): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
1>mtcnn.cpp(106): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
1>mtcnn.cpp(107): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
1>mtcnn.cpp(143): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据
1>mtcnn.cpp(143): warning C4267: “初始化”: 从“size_t”转换到“const int”，可能丢失数据
1>mtcnn.cpp(154): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
1>mtcnn.cpp(155): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
1>mtcnn.cpp(156): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
1>mtcnn.cpp(157): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
1>mtcnn.cpp(192): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
1>mtcnn.cpp(193): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
1>mtcnn.cpp(205): warning C4244: “=”: 从“double”转换到“float”，可能丢失数据
1>mtcnn.cpp(206): warning C4244: “=”: 从“double”转换到“float”，可能丢失数据
1>mtcnn.cpp(207): warning C4244: “=”: 从“float”转换到“int”，可能丢失数据
1>mtcnn.cpp(208): warning C4244: “=”: 从“float”转换到“int”，可能丢失数据
1>mtcnn.cpp(209): warning C4244: “=”: 从“float”转换到“int”，可能丢失数据
1>mtcnn.cpp(210): warning C4244: “=”: 从“float”转换到“int”，可能丢失数据
1>mtcnn.cpp(219): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
1>mtcnn.cpp(259): warning C4244: “初始化”: 从“int”转换到“float”，可能丢失数据
1>mtcnn.cpp(307): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
1>mtcnn.cpp(319): warning C4838: 从“double”转换到“const float”需要收缩转换
1>mtcnn.cpp(319): warning C4305: “初始化”: 从“double”到“const float”截断
1>mtcnn.cpp(348): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
1>mtcnn.cpp(364): warning C4838: 从“double”转换到“const float”需要收缩转换
1>mtcnn.cpp(364): warning C4305: “初始化”: 从“double”到“const float”截断
1>mtcnn.cpp(437): warning C4244: “初始化”: 从“int”转换到“float”，可能丢失数据
1>mtcnn.cpp(507): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
1>mtcnn.cpp(508): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
1>mtcnn.cpp(509): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
1>mtcnn.cpp(510): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
========== 全部重新生成: 成功 0 个，失败 1 个，跳过 0 个 ==========

**Comment by Andrawzyf** [comment]
64位 release

**Comment by qaz734913414** [comment]
你可以尝试32位 release

**Comment by DuckJ** [comment]
这个不同颜色框代表的是不同id的人脸么？体验时候人脸框的颜色很容易就变了

**Comment by qaz734913414** [comment]
@DuckJ 是的
![QQ截图20191101083910](https://user-images.githubusercontent.com/9314219/67995002-3add2e80-fc83-11e9-9d7c-792768c0166d.jpg)
把上面的改为0.1，跟踪效果会好很多
