### ISSUE TITLE
请问下有没有什么办法能够将module改为ZQCNN项目里带口罩的人脸的MTCNN模型呢

### ISSUE THREAD

**Issue by Lin-MZ** [qaz734913414/Ncnn_FaceTrack#4]
现在很多使用场景都是有带口罩的人群的，目前这个版本对于戴口罩的人脸检测和跟踪的情况并不理想，看到
https://github.com/zuoqing1988/ZQCNN
这个项目里提供一组可以检测到带口罩的人脸的MTCNN模型，尝试直接替换module文件夹里面的文件，运行中会出现
“parse magic failed
network graph not ready”
这两个错误提示，请问有没有什么正确的使用姿势呢？？
由于我没接触过深度学习，只是在调用这些库去实现一些功能，在深度学习方面，还有很多不懂的，还希望不吝赐教

**Comment by qaz734913414** [comment]
ncnn的模型不支持解析ZQCNN的模型

**Comment by qaz734913414** [comment]
ZQCNN的模型支持转MNN模型，转出MNN模型之后，你可以试一下这个项目  https://github.com/qaz734913414/MNN_FaceTrack
